name: secure_application
description: Secure app content visibility when user leave app. It will hide content
  in the app switcher and display a frost barrier above locked content when the user get backs
version: 4.0.1
homepage: https://github.com/neckaros/secure_application

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.23
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: org.jezequel.secure_application
        pluginClass: SecureApplicationPlugin
      ios:
        pluginClass: SecureApplicationPlugin 
      web:
        pluginClass: SecureApplicationWeb
        fileName: secure_application_web.dart 
      windows:
        pluginClass: SecureApplicationPlugin
